[package]
name = "tele"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nanoid = "0.4.0"
ctrlc = "3.2"
reqwest = { version = "0.11"}
tokio = { version = "1", features = ["full"] }